### ISSUE TITLE
Using with Typescript and useRef hook throws a type error

### ISSUE THREAD

**Issue by joshuatuscan** [Stanko/animated-scroll-to#64]
Trying to do a simple scroll to element using useRef in a Typescript project but getting the following error:
<img width="574" alt="Screen Shot 2022-10-09 at 6 23 56 PM" src="https://user-images.githubusercontent.com/202188/194782236-e1b7bd1d-6297-4600-a9ac-a37f7f38ff62.png">

Code looks like this.

```
const Home: NextPage<Props> = ({ pagedata }) => {

  const infoRef = useRef<HTMLElement>(null);

  return (
    <>
      <nav>
        <button
          onClick={() => {
            animateScrollTo(infoRef.current);
          }}
        >
          Information
        </button>
      </nav>

      <main className={styles.main}>
        <Projects data={pagedata ? pagedata.data.projects : null} />
      </main>
      <section ref={infoRef} className={styles.info} id="information">
        <InfoSection data={pagedata} />
      </section>
    </>
  );
};

export default Home;
```

Not sure what I'm doing wrong here, seems to want a number as the parameter, but I can't change the definition on the ref or it gets upset that I'm passing an element.

**Comment by Stanko** [comment]
Hey @joshuatuscan,
It is actually expected behavior. Ref has a type of `HTMLElement | null` and `animateScrollTo` doesn't expect `null`. There are two ways to fix it.

A "correct" way would be to check to be sure that ref is not null:
```js
onClick={() => {
  if (infoRef.current) {
    animateScrollTo(infoRef.current);
  }
}}
```

You can also "guarantee" that ref is not null by casting ref to `HTMLElement`. This is safe to do as section will always be rendered (there is no conditional rendering involved) and `onClick` will always happen after the section has been rendered:
```js
onClick={() => {
  animateScrollTo(infoRef.current as HTMLElement);
}}
```

I'm still deciding if `animateScrollTo` should accept `null` as well, and just fail silently in that scenario.

Hope this helps, cheers!

**Comment by joshuatuscan** [comment]
Thanks, that's great and answers my question precisely!
