### ISSUE TITLE
Speed can't be changed

### ISSUE THREAD

**Issue by Ju01110101** [Stanko/animated-scroll-to#67]
It doesn't seem to matter which values I assign to option `speed`: the animation remains identical in all cases. Also tried to play around with `maxDuration` and `minDuration`. Nothing makes the animation speed change.

```
const defaultOptions = {
  maxDuration: 2000,
  minDuration: 2000,
  speed: 3000
}

const defaultOptions = {
  speed: 5000
}

const defaultOptions = {
  maxDuration: 2000,
  speed: 8000
}

animatedScrollTo(el, defaultOptions)
```

**Comment by Stanko** [comment]
Hi @fabricepallaud,

It can be changed, although the parameter name `speed` might be slightly misleading. As it says in the documentation it is actually

> Duration of the scroll per 1000px

So, if you want to slow down, you need to increase this value. It was like this since the first version, so I kept it like this not to break old projects using it. Of course, you'll need to set min/max duration params accordingly.

Here is an example:
https://codesandbox.io/p/sandbox/animated-scroll-to-speed-demo-psmkly

Hope that helps, cheers!

**Comment by Ju01110101** [comment]
I just gave it another try. I played around for 5 minutes trying all kinds of values for these three options: the result is identical in 100% of cases so clearly in my case these values have no impact on the outcome no matter what. Also the link you paste https://codesandbox.io/p/sandbox/animated-scroll-to-speed-demo-psmkly doesn't seem to work:

Error message: NetworkError
Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/typescript@4.4.4/lib/typescript.js' failed to load.
▶ 4 stack frames were collapsed.

**Comment by Stanko** [comment]
I'm not sure, but the speed param and the codesandbox works fine for me in firefox and chrome:

### Firefox 

https://github.com/Stanko/animated-scroll-to/assets/776788/54e8ca13-5218-4b5a-bdfd-b8a0c324a0f7

### Chrome

https://github.com/Stanko/animated-scroll-to/assets/776788/820113f8-07d1-4cfb-96c0-9ce5390c93b7

It might something related to your local configuration/browser?

Could you create a codesandbox or codepen with your examples?
